### ISSUE TITLE
exceeding timeout

### ISSUE THREAD

**Issue by Darxit** [samc621/SneakerBot#101]
i was trying to run a task for a new drop today and i kept getting this error

[5/2/2023, 4:54:47 PM] - TimeoutError: Navigation timeout of 30000 ms exceeded
    at /home/loon/SneakerBot/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:108:111
    at async FrameManager.navigateFrame (/home/loon/SneakerBot/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:131:21)
    at async Frame.goto (/home/loon/SneakerBot/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:512:16)
    at async Page.goto (/home/loon/SneakerBot/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:16)
    at async searchByProductCode (file:///home/loon/SneakerBot/sites/nike.js:179:5)
    at async Object.guestCheckout [as nike] (file:///home/loon/SneakerBot/sites/nike.js:203:5)
    at async file:///home/loon/SneakerBot/helpers/cluster.js:102:34

**Comment by samc621** [comment]
Could you please provide the task payload you are using? I'll need those details to try and reproduce the error.

**Comment by Darxit** [comment]
curl --location -g 'http://127.0.0.1:8050}/v1/tasks' \
--header 'Content-Type: application/json' \
--data-raw '{
    "site_id": 1,
    "url": "https://www.nike.com",
    "product_code": "DV1748-601",
    "style_index": 1,
    "size": "11.5",
    "shipping_speed_index": 0,
    "billing_address_id": 1,
    "shipping_address_id": 2,
    "notification_email_address": "example@gmail.com"
}'
