### ISSUE TITLE
Error running the Dockerfile

### ISSUE THREAD

**Issue by kiddkrypto** [samc621/SneakerBot#58]
I have the .env.docker file in the directory but i am getting the following error. Can you help me get this started?

 docker run -p 5900:5900 -p 8000:8000 --env NODE_ENV=docker --env-file .env.docker sneakerbot
environment name: docker
wait for DB to start
DB host: jerry
running DB migration scripts

> sneakerbot@1.0.0 knex /app
> knex "migrate:latest"

Error: No configuration file found and no commandline connection parameters passed
    at mkConfigObj (/app/node_modules/knex/bin/utils/cli-config-utils.js:11:11)
    at initKnex (/app/node_modules/knex/bin/cli.js:48:7)
    at Command.<anonymous> (/app/node_modules/knex/bin/cli.js:170:32)
    at Command.listener [as _actionHandler] (/app/node_modules/commander/index.js:426:31)
    at Command._parseCommand (/app/node_modules/commander/index.js:1002:14)
    at Command._dispatchSubcommand (/app/node_modules/commander/index.js:953:18)
    at Command._parseCommand (/app/node_modules/commander/index.js:970:12)
    at Command.parse (/app/node_modules/commander/index.js:801:10)
    at Liftoff.invoke (/app/node_modules/knex/bin/cli.js:354:13)
    at Liftoff.execute (/app/node_modules/liftoff/index.js:201:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sneakerbot@1.0.0 knex: `knex "migrate:latest"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sneakerbot@1.0.0 knex script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-10-11T01_21_04_146Z-debug.log
running DB seeder scripts

> sneakerbot@1.0.0 knex /app
> knex "seed:run"

Error: No configuration file found and no commandline connection parameters passed
    at mkConfigObj (/app/node_modules/knex/bin/utils/cli-config-utils.js:11:11)
    at initKnex (/app/node_modules/knex/bin/cli.js:48:7)
    at Command.<anonymous> (/app/node_modules/knex/bin/cli.js:340:7)
    at Command.listener [as _actionHandler] (/app/node_modules/commander/index.js:426:31)
    at Command._parseCommand (/app/node_modules/commander/index.js:1002:14)
    at Command._dispatchSubcommand (/app/node_modules/commander/index.js:953:18)
    at Command._parseCommand (/app/node_modules/commander/index.js:970:12)
    at Command.parse (/app/node_modules/commander/index.js:801:10)
    at Liftoff.invoke (/app/node_modules/knex/bin/cli.js:354:13)
    at Liftoff.execute (/app/node_modules/liftoff/index.js:201:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sneakerbot@1.0.0 knex: `knex "seed:run"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sneakerbot@1.0.0 knex script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-10-11T01_21_05_189Z-debug.log
starting X server and VNC display
starting node server
PORT=5900

The VNC desktop is:      02fa69e16740:0

> sneakerbot@1.0.0 start /app
> node ./app.js

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/app/app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sneakerbot@1.0.0 start: `node ./app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sneakerbot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-10-11T01_21_05_867Z-debug.log

**Comment by samc621** [comment]
@kiddkrypto the `--env-file` flag will let you specify the file to use, can't imagine why that wouldn't work.

**Comment by samc621** [comment]
Closing due to inactivity.
