### ISSUE TITLE
Cannot read properties of undefined (reading 'click')

### ISSUE THREAD

**Issue by mbw290** [samc621/SneakerBot#68]
[1/27/2022, 7:22:43 PM] - No product code supplied, navigating to URL
[1/27/2022, 7:22:46 PM] - Selecting style
[1/27/2022, 7:22:46 PM] - TypeError: Cannot read properties of undefined (reading 'click')
    at Object.exports.guestCheckout (/home/user/SneakerBot/sites/footsites.js:344:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/user/SneakerBot/helpers/cluster.js:103:34

**Comment by mbw290** [comment]
Does anyone have a fully working example?  This doesn't work for me

curl --location -g --request POST '127.0.0.1:8080/v1/tasks' \
--header 'Content-Type: application/json'\
--data-raw '{
    "site_id": 2,
    "url": "https://www.footaction.com/product/nike-challenger-og-mens/W7645003.html",
    "style_index": 1,
    "size": "12",
    "shipping_speed_index": 0,
    "billing_address_id": 2,
    "shipping_address_id": 3,
    "notification_email_address": "XXXX@gmail.com"
}'
