### ISSUE TITLE
can migrate with npx knex migrate:latest

### ISSUE THREAD

**Issue by Un1xMida** [samc621/SneakerBot#84]
i can migrate using npx knex migrate:latest because of this error 
```
knex: Required configuration option 'client' is missing.
Error: knex: Required configuration option 'client' is missing.
    at new Client (D:\botting\node_modules\knex\lib\client.js:58:13)
    at knex (D:\botting\node_modules\knex\lib\knex-builder\Knex.js:12:28)
    at initKnex (D:\botting\node_modules\knex\bin\cli.js:84:10)
    at async Command.<anonymous> (D:\botting\node_modules\knex\bin\cli.js:247:26)
```

**Comment by samc621** [comment]
This error occurs because you have not set your NODE_ENV. Please see the instructions in the README.

**Comment by Un1xMida** [comment]
should i set all properties ? there is no optional properties ?
like the smtp or the credit card info or the captcha.

**Comment by Un1xMida** [comment]
i have set everything but the webhook value
