### ISSUE TITLE
cant migrate the database.

### ISSUE THREAD

**Issue by Un1xMida** [samc621/SneakerBot#85]
```
knex: Required configuration option 'client' is missing.
Error: knex: Required configuration option 'client' is missing.
    at new Client (E:\code-base\sneaker-botting\node_modules\knex\lib\client.js:58:13)
    at knex (E:\code-base\sneaker-botting\node_modules\knex\lib\knex-builder\Knex.js:12:28)
    at initKnex (E:\code-base\sneaker-botting\node_modules\knex\bin\cli.js:63:10)
    at async Command.<anonymous> (E:\code-base\sneaker-botting\node_modules\knex\bin\cli.js:231:26)
```
i have everything in my .env file expect the webhook

**Comment by Un1xMida** [comment]
node version : 16.10.0 
issue fixed by editing the knexfile.js

```
export default {
  client: 'pg',
  connection: {
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    user: process.env.DB_USERNAME,
    database: process.env.DB_NAME,
    password: process.env.DB_PASSWORD
  },
  useNullAsDefault: true,
  debug: true,
  migrations: {
    directory: 'db/migrations',
    tableName: 'knex_migrations'
  },
  seeds: {
    directory: 'db/seeds'
  },
  test: {
    client: 'pg',
    connection: {
      host: process.env.DB_HOST,
      port: process.env.DB_PORT,
      user: process.env.DB_USERNAME,
      database: process.env.DB_NAME,
      password: process.env.DB_PASSWORD
    },
    useNullAsDefault: true,
    debug: true,
    migrations: {
      directory: 'db/migrations',
      tableName: 'knex_migrations'
    },
    seeds: {
      directory: 'db/seeds'
    }
  },
  docker
};
```

**Comment by Un1xMida** [comment]
i can create pr if u want.

**Comment by samc621** [comment]
It's not clear what you changed, but feel free to open a PR.
