### ISSUE TITLE
KnexJs dependency

### ISSUE THREAD

**Issue by aniketfuryrocks** [samc621/SneakerBot#98]
```
SneakerBot on  master [✘!?] is 📦 v1.0.0 via  v19.8.1
⬢ [Docker] ❯ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: knex-mock-client@1.6.2
npm ERR! Found: knex@2.4.0
npm ERR! node_modules/knex
npm ERR!   knex@"^2.4.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer knex@"^1.0.2" from knex-mock-client@1.6.2
npm ERR! node_modules/knex-mock-client
npm ERR!   dev knex-mock-client@"^1.6.2" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: knex@1.0.7
npm ERR! node_modules/knex
npm ERR!   peer knex@"^1.0.2" from knex-mock-client@1.6.2
npm ERR!   node_modules/knex-mock-client
npm ERR!     dev knex-mock-client@"^1.6.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /home/aniket/.npm/_logs/2023-04-22T20_00_21_138Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /home/aniket/.npm/_logs/2023-04-22T20_00_21_138Z-debug-0.log
```

after installing it with `npm install --force`
I get this

```
/home/aniket/Projects/R&D/SneakerBot/node_modules/knex/lib/knex-builder/internal/config-resolver.js:20
    (!parsedConfig.client && !parsedConfig.dialect)
                   ^

TypeError: Cannot read properties of undefined (reading 'client')
    at resolveConfig (/home/aniket/Projects/R&D/SneakerBot/node_modules/knex/lib/knex-builder/internal/config-resolver.js:20:20)
    at knex (/home/aniket/Projects/R&D/SneakerBot/node_modules/knex/lib/knex-builder/Knex.js:14:39)
    at file:///home/aniket/Projects/R&D/SneakerBot/db/index.js:6:12
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
```

Looking at this project and use case. There is actually no requirement of a db. using r/w with simple json files can be done for persistence.

**Comment by samc621** [comment]
Hi @aniketfuryrocks thanks for opening this issue. I just pushed some fixes for the installation issue. Could you please try a fresh install? Please make sure that you are using the same node version specified in the `.nvmrc` file.

As for this error:
`TypeError: Cannot read properties of undefined (reading 'client')`
This is because you did not set the `NODE_ENV` in your environment properly. It must match the name of your .env file and knex configuration. E.g. if you are using `.env.local`, you must set `NODE_ENV=local` before starting the server. Please refer to the README for more information on this.

> Looking at this project and use case. There is actually no requirement of a db. using r/w with simple json files can be done for persistence.

Yes you could absolutely go with a more lightweight database or even no database at all, but I prefer the speed, scalability, and flexibility of a DB with query-builder like `knex`. 

I'm going to close this issue but please feel free to open a new one if any issues persist.
